### ISSUE TITLE
School class buttons not centered

### ISSUE THREAD

**Issue by friendly424** [flowhorn/schulplaner#145]
[download]: https://schulplaner.firebaseapp.com/

## General Troubleshooting

  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request

 
The buttons (see screenshot below) should be centered.
<img src="https://cdn.discordapp.com/attachments/642750994219794442/642793118604722187/Screenshot_20191109-192954.jpg" width=280 height=498></img>
<img src="https://cdn.discordapp.com/attachments/642750994219794442/642793118604722189/Screenshot_20191109-192623.jpg" width=280 height=498></img>

**Comment by Th3Ph4nt0m** [comment]
Sie sollten vielleicht auch vollständig rund sein, nicht mehr länglich.

**Comment by LogischJo** [comment]
Sollte nun behoben sein, könntest du diesen Issue schließen? @Th3Ph4nt0m
