### ISSUE TITLE
"Go Back" button on the login page

### ISSUE THREAD

**Issue by Th3Ph4nt0m** [flowhorn/schulplaner#155]
[download]: https://schulplaner.firebaseapp.com/

## General Troubleshooting

  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request

If the login failed, there is no nice possibility to go back to try again. There should be a "Go Back" button.

**Comment by JBetts97** [comment]
Hello @Th3Ph4nt0m,

Thanks for your help on discord earlier today! 👍 
Just to clarify with this issue, do you mean to improve the error AlertDialog shown when trying to login with an incorrect user/pass?

Something like from this:
![image](https://user-images.githubusercontent.com/38386086/103462680-e1590f80-4d1e-11eb-862a-4a3b66cf9d4a.png)

To this:
![image](https://user-images.githubusercontent.com/38386086/103462663-ac4cbd00-4d1e-11eb-9dbc-51af83badc7c.png)

**Comment by Th3Ph4nt0m** [comment]
I am talking about the screen when the login failed:
<img src="https://user-images.githubusercontent.com/44142235/103464994-61d83a00-4d38-11eb-856f-b0db0471ec53.png" width=200 height=400></img>
There is no actual possibility to go back.

**Comment by JBetts97** [comment]
Sorry @Th3Ph4nt0m , I would just to clarify this request further:

I can replicate this issue by doing the following from first screen:
1. Select 'Google' as sign-in method.
2. Cancel Google authentication (press back on OS button)

So now you are at this screen, you would like a faster way to re-try with Google?
So the expected functionality is to press 'back' instead of pressing tap to 'tap to retry' then 'google'?
Is this correct?

**Comment by Th3Ph4nt0m** [comment]
The `Tap to retry` wasn't working for me. Anyway, this text does not look like "Hey click me" so users will be confused.

**Comment by JBetts97** [comment]
Thanks for the clarification. 👍 
I will try to make the "sign in failed tap to retry" button look a more like a UI button rather than a message.
I will also correct the spelling of "Select methode" to "Select method".

**Comment by Th3Ph4nt0m** [comment]
I already "fixed" the spelling in #154 so you don't need to, this could evoke merge conflicts. Thank you!

**Comment by JBetts97** [comment]
No problem! I will just work on making it look more like a UI button.
